export enum labelSelects {
  alfabeticamenteMayor = "Alfabéticamente Mayor",
  alfabeticamenteMenor = "Alfabéticamente Menor",
  semestreMayor = "Semestre Mayor",
  semestreMenor = "Semestre Menor",
  puntuacionMayor = "Puntuación Mayor",
  puntuacionMenor = "Puntuación Menor",
  noAplicar = "No Aplicar",
  ordenarPor = "Ordenar Por",
  mayor = "Mayor",
  menor = "Menor",

  filtrarEstado = "Filtrar Estado",
  activado = "Habilitado",
  desactivado = "Deshabilitado",
  filtrarSemestre = "Filtrar Semestre",
  filtrarCursosActivos = "Filtrar Cursos Activos",
  sinCursos = "Sin Cursos Activos",
  conCursos = "Con Cursos Activos",
}
