export enum REFERENCE_TO_SITES {
    FACEBOOK = 'https://web.facebook.com/people/Fireploy-DevOps/61578960564476/',
    YOUTUBE = 'https://www.youtube.com/channel/UCoUaSi5mrKEDXKALglJz_uA',
    GITHUB = 'https://github.com/FireployOfficial',
    TEMPLATES_REPOSITORIES = 'https://github.com/FireployOfficial?tab=repositories',
    DOCUMENTATION = 'https://app103.proyectos.fireploy.online',
    TEMPLATE_HTML = "https://github.com/FireployOfficial/Template-HTML",
    TEMPLATE_ANGULAR = "https://github.com/FireployOfficial/Template-Angular",
    TEMPLATE_REACT = "https://github.com/FireployOfficial/Template-React",
    TEMPLATE_NEXTJS = "https://github.com/FireployOfficial/Template-NextJS",
    TEMPLATE_NODEJS = "https://github.com/FireployOfficial/Template-NodeJS",
    TEMPLATE_EXPRESSJS = "https://github.com/FireployOfficial/Template-ExpressJS",
    TEMPLATE_NESTJS = "https://github.com/FireployOfficial/Template-NestJS",
    TEMPLATE_SPRINGBOOT = "https://github.com/FireployOfficial/Template-SpringBoot",
    TEMPLATE_JAVA = "https://github.com/FireployOfficial/Template-Java",
    TEMPLATE_DJANGO = "https://github.com/FireployOfficial/Template-Django",
    TEMPLATE_FASTAPI = "https://github.com/FireployOfficial/Template-FastAPI",
    TEMPLATE_PHP = "https://github.com/FireployOfficial/Template-PHP",
    TEMPLATE_SYMFONY = "https://github.com/FireployOfficial/Template-Symfony",
    TEMPLATE_LARAVEL = "https://github.com/FireployOfficial/Template-Laravel",

    //DOCs
    DOC_TEMPLATES = "https://github.com/FireployOfficialhttps://app103.proyectos.fireploy.online/docs/estudiante/usuario-general/proyectos/introduccion/#templates",
    DOC_HTML = "https://developer.mozilla.org/es/docs/Web/HTML",
    DOC_ANGULAR = "https://angular.dev/",
    DOC_REACT = "https://es.react.dev/",
    DOC_NEXTJS = "https://nextjs.org/",
    DOC_NODEJS = "https://nodejs.org/es",
    DOC_EXPRESSJS = "https://expressjs.com/",
    DOC_NESTJS = "https://nestjs.com/",
    DOC_SPRINGBOOT = "https://spring.io/projects/spring-boot",
    DOC_JAVA = "https://www.oracle.com/java/",
    DOC_DJANGO = "https://www.djangoproject.com/",
    DOC_FASTAPI = "https://fastapi.tiangolo.com/",
    DOC_PHP = "https://www.php.net/",
    DOC_SYMFONY = "https://symfony.com/",
    DOC_LARAVEL = "https://laravel.com/",

    BLOG_TUTORIAL_DEPLOY = 'https://app103.proyectos.fireploy.online/blog/2025/08/31/Despliegue'
}