import { EstadoMateria } from "./materia.estado";

export type SeccionCurso = {
    id?: number,
    titulo: string,
    descripcion: string,
    fechaDeCierre: string,
    fechaDeInicio: string,
    estado: EstadoMateria,
    cursoId: string;
};

// export const seccionesCurso: SeccionCurso[] = [
//     {
//       id: "SEC-001",
//       titulo: "Introducción a la Programación",
//       descripcion: "Conceptos básicos de programación y lógica computacional.",
//       fechaDeInicio: "2024-03-01",
//       fechaDeCierre: "2024-04-01",
//       estado: "A",
//       cursoId: "CURSO-123",
//     },
//     {
//       id: "SEC-002",
//       titulo: "Estructuras de Datos",
//       descripcion: "Estudio de listas, pilas, colas y árboles.",
//       fechaDeInicio: "2024-04-02",
//       fechaDeCierre: "2024-05-02",
//       estado: "A",
//       cursoId: "CURSO-123",
//     },
//     {
//       id: "SEC-003",
//       titulo: "Algoritmos de Ordenamiento",
//       descripcion: "Aprendizaje de algoritmos como quicksort, mergesort y heapsort.",
//       fechaDeInicio: "2024-05-03",
//       fechaDeCierre: "2024-06-03",
//       estado: "I",
//       cursoId: "CURSO-124",
//     },
//     {
//       id: "SEC-004",
//       titulo: "Bases de Datos Relacionales",
//       descripcion: "Conceptos fundamentales sobre bases de datos y SQL.",
//       fechaDeInicio: "2024-06-04",
//       fechaDeCierre: "2024-07-04",
//       estado: "A",
//       cursoId: "CURSO-125",
//     },
//     {
//       id: "SEC-005",
//       titulo: "Desarrollo Web con React",
//       descripcion: "Creación de aplicaciones web modernas con React.",
//       fechaDeInicio: "2024-07-05",
//       fechaDeCierre: "2024-08-05",
//       estado: "A",
//       cursoId: "CURSO-126",
//     },
//     {
//       id: "SEC-006",
//       titulo: "Inteligencia Artificial",
//       descripcion: "Introducción a los conceptos básicos de IA y machine learning.",
//       fechaDeInicio: "2024-08-06",
//       fechaDeCierre: "2024-09-06",
//       estado: "A",
//       cursoId: "CURSO-127",
//     },
//     {
//       id: "SEC-007",
//       titulo: "Ciberseguridad",
//       descripcion: "Principios básicos de seguridad informática y hacking ético.",
//       fechaDeInicio: "2024-09-07",
//       fechaDeCierre: "2024-10-07",
//       estado: "I",
//       cursoId: "CURSO-128",
//     },
//     {
//       id: "SEC-008",
//       titulo: "Desarrollo de Aplicaciones Móviles",
//       descripcion: "Creación de aplicaciones para Android e iOS con Flutter.",
//       fechaDeInicio: "2024-10-08",
//       fechaDeCierre: "2024-11-08",
//       estado: "A",
//       cursoId: "CURSO-129",
//     },
//     {
//       id: "SEC-009",
//       titulo: "Redes de Computadoras",
//       descripcion: "Fundamentos de redes y protocolos de comunicación.",
//       fechaDeInicio: "2024-11-09",
//       fechaDeCierre: "2024-12-09",
//       estado: "A",
//       cursoId: "CURSO-130",
//     },
//     {
//       id: "SEC-010",
//       titulo: "Análisis de Datos",
//       descripcion: "Uso de herramientas para el análisis y visualización de datos.",
//       fechaDeInicio: "2024-12-10",
//       fechaDeCierre: "2025-01-10",
//       estado: "A",
//       cursoId: "CURSO-131",
//     },
//   ];
  