import { Usuario } from "@modules/usuarios/types/usuario";

export type EstudianteEjemplo = Pick<Usuario, 'estado' | 'nombres' | 'apellidos' | 'fechaDeNacimiento' | 'sexo' | 'correo' | 'fotoDePerfil' | 'estFechaInicio' | 'id'>;

export const estudiantesEjemplo: EstudianteEjemplo[] = [
  {
    estado: "A",
    nombres: "Emilia",
    apellidos: "Pérez",
    fechaDeNacimiento: "2002-04-22",
    sexo: "M",
    correo: "pingoalex22@gmail.com",
    fotoDePerfil: "https://example.com/foto1.jpg",
    estFechaInicio: "1990-05-15",
    id: 23,
  },
  {
    estado: "I",
    nombres: "Joaquín",
    apellidos: "López",
    fechaDeNacimiento: "1995-08-12",
    sexo: "M",
    correo: "joaquin.lopez@example.com",
    fotoDePerfil: "https://example.com/foto2.jpg",
    estFechaInicio: "2015-06-30",
    id: 24,
  },
  {
    estado: "A",
    nombres: "Valentina",
    apellidos: "García",
    fechaDeNacimiento: "1998-11-03",
    sexo: "F",
    correo: "valentina.garcia@example.com",
    fotoDePerfil: "https://example.com/foto3.jpg",
    estFechaInicio: "2017-02-20",
    id: 25,
  },
  {
    estado: "A",
    nombres: "Andrés",
    apellidos: "Martínez",
    fechaDeNacimiento: "1993-05-18",
    sexo: "M",
    correo: "andres.martinez@example.com",
    fotoDePerfil: "https://example.com/foto4.jpg",
    estFechaInicio: "2012-09-10",
    id: 26,
  },
  {
    estado: "A",
    nombres: "Camila",
    apellidos: "Fernández",
    fechaDeNacimiento: "2000-07-25",
    sexo: "F",
    correo: "camila.fernandez@example.com",
    fotoDePerfil: "https://example.com/foto5.jpg",
    estFechaInicio: "2018-04-15",
    id: 27,
  },
  {
    estado: "I",
    nombres: "Sebastián",
    apellidos: "Torres",
    fechaDeNacimiento: "1991-02-10",
    sexo: "M",
    correo: "sebastian.torres@example.com",
    fotoDePerfil: "https://example.com/foto6.jpg",
    estFechaInicio: "2009-12-05",
    id: 28,
  },
  {
    estado: "A",
    nombres: "Isabella",
    apellidos: "Ramírez",
    fechaDeNacimiento: "1996-09-14",
    sexo: "F",
    correo: "isabella.ramirez@example.com",
    fotoDePerfil: "https://example.com/foto7.jpg",
    estFechaInicio: "2014-07-21",
    id: 29,
  },
  {
    estado: "A",
    nombres: "Mateo",
    apellidos: "Hernández",
    fechaDeNacimiento: "1994-03-30",
    sexo: "M",
    correo: "mateo.hernandez@example.com",
    fotoDePerfil: "https://example.com/foto8.jpg",
    estFechaInicio: "2011-10-11",
    id: 30,
  },
  {
    estado: "A",
    nombres: "Sofía",
    apellidos: "Gómez",
    fechaDeNacimiento: "1997-06-05",
    sexo: "F",
    correo: "sofia.gomez@example.com",
    fotoDePerfil: "https://example.com/foto9.jpg",
    estFechaInicio: "2016-03-28",
    id: 31,
  },
  {
    estado: "I",
    nombres: "Diego",
    apellidos: "Díaz",
    fechaDeNacimiento: "1990-12-19",
    sexo: "M",
    correo: "diego.diaz@example.com",
    fotoDePerfil: "https://example.com/foto10.jpg",
    estFechaInicio: "2008-08-17",
    id: 32,
  },
];
