import { UsuarioService } from "@modules/usuarios/types/services.usuario";

export const usuariosEjemplo: UsuarioService[] = [
  {
    estado: "A",
    id: 1,
    nombre: "Maria alberta",
    apellido: "Pérez",
    fecha_nacimiento: "1995-08-20T00:00:00.000Z",
    sexo: "M",
    descripcion: "Desarrollador de software con experiencia en NestJS.",
    correo: "Admin@gmail.com",
    contrasenia: "$2b$10$6Lw3rcE0L.o1KAG/pKb4.eoVQf/rX.9Fkxa3bGItRFDULPHDC7zV2",
    red_social:
      '{"linkedin":"www.linkedin.com/holaMundo","facebook":"","instagram":"","x":""}',
    foto_perfil:
      "https://storage.googleapis.com/fireploy-57702.firebasestorage.app/uploads/User_Image_1.png",
    tipo: "Estudiante",
    est_fecha_inicio: "1990-05-15T00:00:00.000Z",
  },
  {
    estado: "A",
    id: 2,
    nombre: "Julian",
    apellido: "Alvarez",
    fecha_nacimiento: "1990-05-15T00:00:00.000Z",
    sexo: "M",
    descripcion: "Desarrollador de software con 5 años de experiencia",
    correo: "Julian.admin@gmail.com",
    contrasenia: "$2b$10$yp6/cEyGt2VuXcN2NFSAi.rnrwmyPWM2zinLemBPWNbO2ZSCrcn6W",
    red_social: '{"facebook":"","instagram":"","linkedin":"","x":""}',
    foto_perfil:
      "https://storage.googleapis.com/fireploy-57702.firebasestorage.app/uploads/User_Image_2.png",
    tipo: "Administrador",
  },
  {
    estado: "A",
    id: 3,
    nombre: "Rodrigo",
    apellido: "Malaver",
    fecha_nacimiento: "1995-08-20T00:00:00.000Z",
    sexo: "M",
    descripcion: "Desarrollador de software con experiencia en NestJS.",
    correo: "quiroz.admin@gmail.com",
    contrasenia: "$2b$10$zU7ixk.BYpBBvlHpXPnQHu9JCEUevt4GLttanKls8ezbEFhBni.AO",
    red_social:
      '{"linkedin":"www.linkedin.com/a","facebook":"","instagram":"","x":""}',
    foto_perfil:
      "https://storage.googleapis.com/fireploy-57702.firebasestorage.app/uploads/User_Image_3.png",
    tipo: "Administrador",
  },
  {
    estado: "A",
    id: 4,
    nombre: "Rodrigo Andrés",
    apellido: "Malaver Suárez",
    fecha_nacimiento: "2002-04-22T00:00:00.000Z",
    sexo: "M",
    descripcion: "Desarrollador de software con 25 años de experiencia",
    correo: "rodrigo.admin@gmail.com",
    contrasenia: "$2b$10$dT0EWg/gLlKNzaVb5kZwJe8kJJRvKatkHz779PMwsHStTvbJPJiIK",
    red_social: '{"facebook":"","instagram":"","linkedin":"","x":""}',
    foto_perfil:
      "https://storage.googleapis.com/fireploy-57702.firebasestorage.app/uploads/User_Image_4.png",
    tipo: "Administrador",
  },
  {
    estado: "A",
    id: 5,
    nombre: "Julian",
    apellido: "Alvarez",
    fecha_nacimiento: "1990-05-15T00:00:00.000Z",
    sexo: "M",
    descripcion: "Desarrollador de software con 5 años de experiencia",
    correo: "Test.admin@gmail.com",
    contrasenia: "$2b$10$BYPrSMzo3KVR26yVem..teDESMDbU7Pxb1taf.75zkIiIol2bCfxi",
    red_social: "https://twitter.com/juanperez",
    foto_perfil: "https://example.com/foto.jpg",
    tipo: "Estudiante",
    est_fecha_inicio: "1990-05-15T00:00:00.000Z",
  },
  {
    estado: "A",
    id: 6,
    nombre: "YA",
    apellido: "YA",
    fecha_nacimiento: "2002-04-22T00:00:00.000Z",
    sexo: "M",
    descripcion: "",
    correo: "rodrigo.admiSn@gmail.com",
    contrasenia: "$2b$10$ZCxiGXQANpB7wL/j2xEGP.7pU3AfOlA46Rkzqd2NuD3DZFPzw2Vna",
    red_social: '{"facebook":"","instagram":"","linkedin":"","x":""}',
    foto_perfil:
      "https://storage.googleapis.com/fireploy-57702.firebasestorage.app/uploads/User_Image_6.png",
    tipo: "Docente",
  },
  {
    estado: "A",
    id: 7,
    nombre: "YA",
    apellido: "YAS",
    fecha_nacimiento: "2002-04-22T00:00:00.000Z",
    sexo: "M",
    descripcion: "",
    correo: "rodrigosdfgadmin@gmail.com",
    contrasenia: "$2b$10$.c.wSae3DlkW3jLRxCgbf.9twYrnA2kbtNAPmrWoRyiLHSC.JanmC",
    red_social: '{"facebook":"","instagram":"","linkedin":"","x":""}',
    foto_perfil:
      "https://storage.googleapis.com/fireploy-57702.firebasestorage.app/uploads/User_Image_7.png",
    tipo: "Docente",
  },
  {
    estado: "A",
    id: 8,
    nombre: "Juliasn",
    apellido: "Alsvarez",
    fecha_nacimiento: "1990-05-15T00:00:00.000Z",
    sexo: "M",
    descripcion: "Desarrollador de software con 5 años de experiencia",
    correo: "x@sad.asd",
    contrasenia: "$2b$10$qMkravkSy1W3zwo3bLH18.rPyJVZNRAZkdna./THz4K0H6CgnzITq",
    red_social: "https://twitter.com/juanperez",
    foto_perfil:
      "https://storage.googleapis.com/fireploy-57702.firebasestorage.app/uploads/User_Image_8.png",
    tipo: "Estudiante",
    est_fecha_inicio: "1990-05-15T00:00:00.000Z",
  },
  {
    estado: "A",
    id: 9,
    nombre: "Juliasn",
    apellido: "Alsvarez",
    fecha_nacimiento: "1990-05-15T00:00:00.000Z",
    sexo: "M",
    descripcion: "Desarrollador de software con 5 años de experiencia",
    correo: "x@saasdd.asd",
    contrasenia: "$2b$10$TKupoHH1Q1ruRzX76bybAe5GkOfPUprqDqIZqWDnUKQeAsYfg8G.S",
    red_social: "https://twitter.com/juanperez",
    foto_perfil: "https://example.com/foto.jpg",
    tipo: "Estudiante",
    est_fecha_inicio: "1990-05-15T00:00:00.000Z",
  },
  {
    estado: "A",
    id: 10,
    nombre: "Juliasn",
    apellido: "Alsvarez",
    fecha_nacimiento: "1990-05-15T00:00:00.000Z",
    sexo: "M",
    descripcion: "Desarrollador de software con 5 años de experiencia",
    correo: "xasdasd@saasdd.asd",
    contrasenia: "$2b$10$9DdBebqt0VMr.KAriClPQulkoVEx5smcTGE3ZNSDhIfZzG5hfE27y",
    red_social: "https://twitter.com/juanperez",
    foto_perfil: "https://example.com/foto.jpg",
    tipo: "Estudiante",
    est_fecha_inicio: "1990-05-15T00:00:00.000Z",
  },
  {
    estado: "A",
    id: 11,
    nombre: "Juliasn",
    apellido: "Alsvarez",
    fecha_nacimiento: "1990-05-15T00:00:00.000Z",
    sexo: "M",
    descripcion: "Desarrollador de software con 5 años de experiencia",
    correo: "rodrigoasdasdsdfgadmin@gmail.com",
    contrasenia: "$2b$10$280WdDoC4p5EgcdMXQ9vD.ZEh3m4WCceOxIWtrUi.64k8ih1HeBIO",
    red_social: "https://twitter.com/juanperez",
    foto_perfil: "https://example.com/foto.jpg",
    tipo: "Estudiante",
    est_fecha_inicio: "1990-05-15T00:00:00.000Z",
  },
  {
    estado: "A",
    id: 12,
    nombre: "Juliasn",
    apellido: "Alsvarez",
    fecha_nacimiento: "1990-05-15T00:00:00.000Z",
    sexo: "M",
    descripcion: "Desarrollador de software con 5 años de experiencia",
    correo: "as@gmail.com",
    contrasenia: "$2b$10$/ax2wxMEmjJ1aBpzBi8E8OP1hnWQmPKsTxGyju1.hhFuPRsXIQeR.",
    red_social: "https://twitter.com/juanperez",
    foto_perfil: "https://example.com/foto.jpg",
    tipo: "Estudiante",
    est_fecha_inicio: "1990-05-15T00:00:00.000Z",
  },
  {
    estado: "A",
    id: 13,
    nombre: "YA",
    apellido: "YA",
    fecha_nacimiento: "2002-04-22T00:00:00.000Z",
    sexo: "M",
    descripcion: "",
    correo: "kghjoism2@gmail.com",
    contrasenia: "$2b$10$oggo5hVbusH0ZpyZbqvxSOdPH6eUxbM0jFQcKnjZcc.l7qZN4dKhm",
    red_social: '{"facebook":"","instagram":"","linkedin":"","x":""}',
    foto_perfil:
      "https://cdn.pixabay.com/photo/2024/12/30/13/06/moped-9300285_1280.jpg",
    tipo: "Docente",
  },
  {
    estado: "A",
    id: 14,
    nombre: "Juliasn",
    apellido: "Alsvarez",
    fecha_nacimiento: "1990-05-15T00:00:00.000Z",
    sexo: "M",
    descripcion: "Desarrollador de software con 5 años de experiencia",
    correo: "kghjoissm2@gmail.com",
    contrasenia: "$2b$10$7vxWV8CadoRICSzcR12U2uoUF.zc84FrpKOtRHJbUvhv2sQ0sabzG",
    red_social: "https://twitter.com/juanperez",
    foto_perfil: "https://example.com/foto.jpg",
    tipo: "Estudiante",
    est_fecha_inicio: "1990-05-15T00:00:00.000Z",
  },
  {
    estado: "A",
    id: 15,
    nombre: "sdf",
    apellido: "ads",
    fecha_nacimiento: "2002-04-22T00:00:00.000Z",
    sexo: "M",
    descripcion: "",
    correo: "rodrasdgo.admasdin@gmail.com",
    contrasenia: "$2b$10$hDKzjNs.kR2eYeUXOTwH.u3iz0ho7vKCZg.ZUUnO8//CmD9zCmp/m",
    red_social: '{"facebook":"","instagram":"","linkedin":"","x":""}',
    foto_perfil:
      "https://cdn.pixabay.com/photo/2024/12/30/13/06/moped-9300285_1280.jpg",
    tipo: "Estudiante",
    est_fecha_inicio: "2002-04-22T00:00:00.000Z",
  },
  {
    estado: "A",
    id: 16,
    nombre: "Juan",
    apellido: "Pérez",
    fecha_nacimiento: "1990-05-15T00:00:00.000Z",
    sexo: "M",
    descripcion: "Desarrollador de software con 5 años de experiencia",
    correo: "Docente1@gmail.com",
    contrasenia: "$2b$10$Ox7y6aCySHvI1ot2Iw7XDumsUl.v7RWCHLg3Dfi6X.oGF4Usx8bcu",
    red_social: "https://twitter.com/juanperez",
    foto_perfil: "https://example.com/foto.jpg",
    tipo: "Docente",
  },
  {
    estado: "A",
    id: 17,
    nombre: "Juliasn",
    apellido: "Alsvarez",
    fecha_nacimiento: "1990-05-15T00:00:00.000Z",
    sexo: "M",
    descripcion: null,
    correo: "kghjoissm2@sgmail.com",
    contrasenia: "$2b$10$vkIXFLNzbvBoVcvK9dvHwO0sJcdbOL4kVSJ9JsP4O.IiSVN3j1JTu",
    red_social: "https://twitter.com/juanperez",
    foto_perfil: "https://example.com/foto.jpg",
    tipo: "Estudiante",
    est_fecha_inicio: "1990-05-15T00:00:00.000Z",
  },
  {
    estado: "A",
    id: 18,
    nombre: "Juliasn",
    apellido: "Alsvarez",
    fecha_nacimiento: "1990-05-15T00:00:00.000Z",
    sexo: "M",
    descripcion: "Desarrollador de software con 5 años de experiencia",
    correo: "kghjoissms2@gmail.com",
    contrasenia: "$2b$10$mgb5OQ2wl7hAKEuaGNULYOP6GTLdnGhtqz9R8gZugoHT37U6c116C",
    red_social: "https://twitter.com/juanperez",
    foto_perfil: "https://example.com/foto.jpg",
    tipo: "Estudiante",
    est_fecha_inicio: "1990-05-15T00:00:00.000Z",
  },
  {
    estado: "A",
    id: 19,
    nombre: "A",
    apellido: "A",
    fecha_nacimiento: "2002-04-22T00:00:00.000Z",
    sexo: "O",
    descripcion: "",
    correo: "A@A.es",
    contrasenia: "$2b$10$RGELLBOTg2k89KhURxi9xenYmor2tWkN3BLlxtFYGn6849.5SPk3y",
    red_social: '{"facebook":"","instagram":"","linkedin":"","x":""}',
    foto_perfil:
      "https://cdn.pixabay.com/photo/2024/12/30/13/06/moped-9300285_1280.jpg",
    tipo: "Estudiante",
    est_fecha_inicio: "2002-04-22T00:00:00.000Z",
  },
  {
    estado: "A",
    id: 20,
    nombre: "Juliasn",
    apellido: "Alsvarez",
    fecha_nacimiento: "1990-05-15T00:00:00.000Z",
    sexo: "M",
    descripcion: "Desarrollador de software con 5 años de experiencia",
    correo: "kghjoissms2d@gmail.com",
    contrasenia: "$2b$10$IGDyVdk1mmU5g7Hlac6o2.H8kOBqOQLYkkSe6bmec6oDRo3aKhb2i",
    red_social: "https://twitter.com/juanperez",
    foto_perfil: "https://example.com/foto.jpg",
    tipo: "Estudiante",
    est_fecha_inicio: "1990-05-15T00:00:00.000Z",
  },
  {
    estado: "A",
    id: 21,
    nombre: "Luis Carlos",
    apellido: "Sarmiento Angulo",
    fecha_nacimiento: "2002-04-22T00:00:00.000Z",
    sexo: "O",
    descripcion: "",
    correo: "luisk@ufps.edu.co",
    contrasenia: "$2b$10$4sHNbb2iyerz5T6mxZIazenh20VkYzmXniOpZJdzlN2NBSHqeAXF2",
    red_social: '{"facebook":"","instagram":"","linkedin":"","x":""}',
    foto_perfil:
      "https://cdn.pixabay.com/photo/2024/12/30/13/06/moped-9300285_1280.jpg",
    tipo: "Estudiante",
    est_fecha_inicio: "2020-04-19T00:00:00.000Z",
  },
  {
    estado: "A",
    id: 22,
    nombre: "FOTO TEST",
    apellido: "A",
    fecha_nacimiento: "2002-04-22T00:00:00.000Z",
    sexo: "M",
    descripcion: "",
    correo: "rodrigoandresmasu@ufps.edu.co",
    contrasenia: "$2b$10$ngv050/9LzrfNR7PyQfuGu81QvBTKHe1lxZJbc41ksicCMA516H26",
    red_social: '{"facebook":"","instagram":"","linkedin":"","x":""}',
    foto_perfil:
      "https://storage.googleapis.com/fireploy-57702.firebasestorage.app/uploads/User_Image_22.png",
    tipo: "Estudiante",
    est_fecha_inicio: "2002-04-22T00:00:00.000Z",
  },
  {
    estado: "A",
    id: 23,
    nombre: "Emilia",
    apellido: "Pérez",
    fecha_nacimiento: "2002-04-22T00:00:00.000Z",
    sexo: "M",
    descripcion: "Desarrollador de software con 5 años de experiencia",
    correo: "pingoalex22@gmail.com",
    contrasenia: "$2b$10$3OnH0EcadGB/adwBLLdzd.QMcwE1A9445NxKyFJatSRELernHGD0a",
    red_social: "https://twitter.com/juanperez",
    foto_perfil: "https://example.com/foto.jpg",
    tipo: "Estudiante",
    est_fecha_inicio: "1990-05-15T00:00:00.000Z",
  },
  {
    estado: "A",
    id: 24,
    nombre: "Juan",
    apellido: "Pérez",
    fecha_nacimiento: "1985-03-10T00:00:00.000Z",
    sexo: "M",
    descripcion: "Administrador del sistema",
    correo: "juan@example.com",
    contrasenia: "$2b$10$rmAlZ6vaAJURejS1cUzopOaOeli.dLbEezAqdGHRYPJ4a1cGRQlcO",
    red_social: "@juan_admin",
    foto_perfil: "juan.jpg",
    tipo: "Administrador",
  },
  {
    estado: "A",
    id: 25,
    nombre: "María",
    apellido: "Gómez",
    fecha_nacimiento: "1990-07-15T00:00:00.000Z",
    sexo: "F",
    descripcion: "Docente de matemáticas",
    correo: "maria@example.com",
    contrasenia: "$2b$10$kqix0nO2aPzoQg21woiOGOA9.HhIbETddjZNCXhrXqg0.eBO5DDOC",
    red_social: "@maria_docente",
    foto_perfil: "maria.png",
    tipo: "Docente",
  },
  {
    estado: "A",
    id: 26,
    nombre: "Carlos",
    apellido: "Rodríguez",
    fecha_nacimiento: "2000-05-12T00:00:00.000Z",
    sexo: "M",
    descripcion: "Estudiante de ingeniería",
    correo: "carlos@example.com",
    contrasenia: "$2b$10$wnR6NAsKyZpcXqjOrpdvKOXuojkBQ7zx2c4Omh2dJr69Z8sc4L5vu",
    red_social: "@carlos_ig",
    foto_perfil: "carlos.jpeg",
    tipo: "Estudiante",
    est_fecha_inicio: null,
  },
  {
    estado: "A",
    id: 27,
    nombre: "Ana",
    apellido: "López",
    fecha_nacimiento: "1999-08-22T00:00:00.000Z",
    sexo: "F",
    descripcion: "Estudiante de diseño",
    correo: "ana@example.com",
    contrasenia: "$2b$10$zUukD6LGmRo.Io.TfloTJ.phip/h9ziNcZwi81Z7UVlIC93RgTMyW",
    red_social: "@ana_fb",
    foto_perfil: "ana.jpg",
    tipo: "Estudiante",
    est_fecha_inicio: null,
  },
  {
    estado: "A",
    id: 28,
    nombre: "Comercial",
    apellido: "Bolixar",
    fecha_nacimiento: "2002-04-22T00:00:00.000Z",
    sexo: "M",
    descripcion: "a",
    correo: "rodrigoa.admin@gmail.com",
    contrasenia: "$2b$10$5gZVgU0kmncBFv0qXxJ9aOk3WAx8W4tWiCXVnD0WMsuzmPuRptTFe",
    red_social: '{"facebook":"","instagram":"","linkedin":"","x":""}',
    foto_perfil:
      "https://storage.googleapis.com/fireploy-57702.firebasestorage.app/uploads/User_Image_28.png",
    tipo: "Estudiante",
    est_fecha_inicio: "2002-04-22T00:00:00.000Z",
  },
  {
    estado: "A",
    id: 29,
    nombre: "Andres",
    apellido: "Silver",
    fecha_nacimiento: "2002-04-22T00:00:00.000Z",
    sexo: "M",
    descripcion: "",
    correo: "andresuiva@ufps.edu.co",
    contrasenia: "$2b$10$h2ECtiGshq9F0yr1rpK8JOHr8ezu6o7lnKchwPfnlF2Q9SSzyX3Ce",
    red_social: '{"facebook":"","instagram":"","linkedin":"","x":""}',
    foto_perfil:
      "https://cdn.pixabay.com/photo/2016/11/14/17/39/person-1824147_1280.png",
    tipo: "Estudiante",
    est_fecha_inicio: "2004-12-11T00:00:00.000Z",
  },
  {
    estado: "A",
    id: 30,
    nombre: "ADMIN 1",
    apellido: "ADMIN 1",
    fecha_nacimiento: "2002-04-22T00:00:00.000Z",
    sexo: "M",
    descripcion: "",
    correo: "rodrigo.adsdmin@gmail.com",
    contrasenia: "$2b$10$RcQ.0Dyms6Bi2Uiv3DcAEOpZUgdPWvixHRrQlhhxBGt.y8BHBD756",
    red_social: '{"facebook":"","instagram":"","linkedin":"","x":""}',
    foto_perfil:
      "https://cdn.pixabay.com/photo/2016/11/14/17/39/person-1824147_1280.png",
    tipo: "Administrador",
  },
];
